---
kind: pipeline
type: docker
name: default

steps:
  - name: testing
    image: golang:1.17
    commands:
      - echo yak
      - make test
    when:
      branch:
          include:
            - tests
