---
kind: pipeline
type: docker
name: default

steps:
- name: testing
  image: golang:1.17
  volumes:
    - name: deps
      path: /go
  commands:
    - make test
  when:
    branch:
        include:
          - tests
- name: build
  image: golang:1.17
  volumes:
    - name: deps
      path: /go
  commands:
    - GOOS=linux GOARCH=amd64 go build -o ./using-kit/kit-server-d ./using-kit
    - mv ./using-kit/kit-server-d /go/bin/
    - ls /go/bin/
- name: publish
  image: plugins/ecr
  privileged: true
  settings:
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    repo: using-kit
    registry: 644165228998.dkr.ecr.us-east-1.amazonaws.com
    tags:
      - 0.0.1
    dockerfile: ./using-kit/Dockerfile
    force_tag: true
  volumes:
    - name: deps
      path: /go
  commands:
    - ls /go/bin/
    - env
  when:
    branch:
      include:
        - tests
volumes:
- name: deps
  temp: {}
