---
kind: pipeline
type: docker
name: default

steps:
  - name: testing
    image: golang:1.17
    environment:
      GO111MODULE="off"
    commands:
      - export GOPATH=$HOME
      - echo yak
      - make test
    when:
      branch:
          include:
            - tests
